// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFbBXjRcHijo-skipK0ysdDztvCb5P9oU',
    appId: '1:1090878587702:web:fcad7b643c7d784d84a997',
    messagingSenderId: '1090878587702',
    projectId: 'findoutmole',
    authDomain: 'findoutmole.firebaseapp.com',
    storageBucket: 'findoutmole.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD73lY0wv82ulErAw8nVbaRFE8Th1LigRs',
    appId: '1:1090878587702:android:812a753afc27384784a997',
    messagingSenderId: '1090878587702',
    projectId: 'findoutmole',
    storageBucket: 'findoutmole.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5uLuQ7p2gRNw-cO35fu0QQJjRd3LfQJo',
    appId: '1:1090878587702:ios:1d90ba99fb9d220584a997',
    messagingSenderId: '1090878587702',
    projectId: 'findoutmole',
    storageBucket: 'findoutmole.firebasestorage.app',
    iosBundleId: 'com.example.proyectofindoutmole',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFbBXjRcHijo-skipK0ysdDztvCb5P9oU',
    appId: '1:1090878587702:web:6ad70511ebaaf66e84a997',
    messagingSenderId: '1090878587702',
    projectId: 'findoutmole',
    authDomain: 'findoutmole.firebaseapp.com',
    storageBucket: 'findoutmole.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5uLuQ7p2gRNw-cO35fu0QQJjRd3LfQJo',
    appId: '1:1090878587702:ios:1d90ba99fb9d220584a997',
    messagingSenderId: '1090878587702',
    projectId: 'findoutmole',
    storageBucket: 'findoutmole.firebasestorage.app',
    iosBundleId: 'com.example.proyectofindoutmole',
  );

}